query GetUsers {
  getUsers {
    id
    pseudo
    email
    bestScore
  }
}

query Get10BestUsers {
  get10BestUsers {
    id
    pseudo
    bestScore
  }
}

mutation CreateUser($data: UsersInput!) {
  createUser(data: $data) {
    id
    pseudo
    email
  }
}

mutation UpdateUserBestScore($data: UpdateUserBestScoreInput!) {
  updateUserBestScore(data: $data)
}

mutation DeleteUser($userId: Float!) {
  deleteUser(userId: $userId)
}